version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: gabinet_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gabinet_db
      TZ: Europe/Warsaw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - med-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: gabinet_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - med-network

  backend:
    build: ./backend
    container_name: gabinet_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin123
      DB_NAME: gabinet_db
      JWT_SECRET: super_tajne_haslo_dev
      CORS_ORIGIN: http://localhost:5173
      TZ: Europe/Warsaw
    depends_on:
      - postgres
    networks:
      - med-network
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend
    container_name: gabinet_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - med-network
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev -- --host

volumes:
  postgres_data:
  pgadmin_data:

networks:
  med-network:
    driver: bridge